// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasmBlazorAppAssignment.Data;

#nullable disable

namespace WasmBlazorAppAssignment.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WasmBlazorAppAssignment.Shared.Entities.VehicleSaleDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<double>("MSRP")
                        .HasColumnType("float");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleSaleDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classification = 0,
                            Colour = "Red",
                            Cost = 1500.0,
                            MSRP = 3000.0,
                            Make = "Audi",
                            Model = "A4"
                        },
                        new
                        {
                            Id = 2,
                            Classification = 1,
                            Colour = "Blue",
                            Cost = 4000.0,
                            MSRP = 9000.0,
                            Make = "Chevrolet",
                            Model = "Camaro"
                        },
                        new
                        {
                            Id = 3,
                            Classification = 2,
                            Colour = "Red",
                            Cost = 5000.0,
                            MSRP = 12000.0,
                            Make = "Dodge",
                            Model = "Ram"
                        },
                        new
                        {
                            Id = 4,
                            Classification = 2,
                            Colour = "Black",
                            Cost = 1500.0,
                            MSRP = 3000.0,
                            Make = "Audi",
                            Model = "A4"
                        },
                        new
                        {
                            Id = 5,
                            Classification = 0,
                            Colour = "Blue",
                            Cost = 40000.0,
                            MSRP = 50000.0,
                            Make = "Chevrolet",
                            Model = "Camaro"
                        },
                        new
                        {
                            Id = 6,
                            Classification = 0,
                            Colour = "Red",
                            Cost = 5000.0,
                            MSRP = 12000.0,
                            Make = "Dodge",
                            Model = "Ram"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
